const defaults=[
 {brand:'BYREDO',name:'Bal d’Afrique',type:'women',price:18900,notes:'Бергамот · Нероли · Ветивер',tone:'sand'},
 {brand:'Maison Margiela',name:'REPLICA Jazz Club',type:'men',price:8900,notes:'Ром · Табак · Ваниль',tone:'amber'},
 {brand:'Le Labo',name:'Santal 33',type:'unisex',price:24900,notes:'Кардамон · Сандал · Кедр',tone:'clay'},
 {brand:'Diptyque',name:'Philosykos',type:'unisex',price:15400,notes:'Инжир · Кокос · Древесина',tone:'green'},
 {brand:'Aesop',name:'Hwyl',type:'men',price:12600,notes:'Кипарис · Ладан · Ветивер',tone:'olive'},
 {brand:'Narciso Rodriguez',name:'For Her Musc Noir',type:'women',price:11200,notes:'Слива · Мускус · Замша',tone:'rose'},
 {brand:'Jo Malone',name:'Wood Sage & Sea Salt',type:'unisex',price:9800,notes:'Амброксан · Грейпфрут · Шалфей',tone:'blue'},
 {brand:'Kilian',name:'Angels’ Share',type:'unisex',price:33500,notes:'Коньяк · Корица · Бобы тонка',tone:'gold'}
];
let products=JSON.parse(localStorage.getItem('aura-products')||'null')||defaults,cart=[],filter='all';
const money=n=>n.toLocaleString('ru-RU')+' ₽'; const $=s=>document.querySelector(s);
function render(){let q=($('#search').value||'').toLowerCase(),list=products.filter(p=>(filter==='all'||p.type===filter)&&(`${p.brand} ${p.name} ${p.notes}`.toLowerCase().includes(q)));if($('#sort').value==='priceAsc')list.sort((a,b)=>a.price-b.price);if($('#sort').value==='priceDesc')list.sort((a,b)=>b.price-a.price);$('#resultCount').textContent=`${list.length} ароматов`;
$('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-art ${p.tone}"><span class="heart">♡</span><span class="mini-bottle">${p.brand[0]}</span><small>${p.type==='unisex'?'UNISEX':p.type==='women'?'POUR FEMME':'POUR HOMME'}</small></div><div class="product-info"><p>${p.brand}</p><h3>${p.name}</h3><small>${p.notes}</small><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-index="${products.indexOf(p)}">В корзину +</button></div></div></article>`).join(''):'<p class="empty">По вашему запросу ничего не найдено.</p>';document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.index]);renderCart();openDrawer()})}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItemsCount').textContent=cart.length?`(${cart.length})`:'';$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div class="cart-thumb ${p.tone}">${p.brand[0]}</div><div><b>${p.name}</b><small>${p.brand}</small></div><strong>${money(p.price)}</strong><button data-remove="${i}">×</button></div>`).join(''):'<p class="empty">Корзина пока пуста.<br>Добавьте аромат, который понравился.</p>';$('#cartTotal').textContent=money(cart.reduce((s,p)=>s+p.price,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}
function openDrawer(){$('#drawer').classList.add('open');$('#overlay').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});$('#search').oninput=render;$('#sort').onchange=render;$('#openCart').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;$('#mobileMenu').onclick=()=>document.querySelector('.main-nav').classList.toggle('show');$('#checkout').onclick=()=>alert(cart.length?'Спасибо! Менеджер свяжется с вами для подтверждения заказа.':'Добавьте аромат в корзину.');$('#subscribe').onsubmit=e=>{e.preventDefault();alert('Спасибо! Вы подписаны на новости AURA.');e.target.reset()};render();renderCart();