const defaults=[
 {brand:'BYREDO',name:'Bal d’Afrique',type:'women',price:18900,notes:'Бергамот · Нероли · Ветивер',tone:'sand'},
 {brand:'Maison Margiela',name:'REPLICA Jazz Club',type:'men',price:8900,notes:'Ром · Табак · Ваниль',tone:'amber'},
 {brand:'Le Labo',name:'Santal 33',type:'unisex',price:24900,notes:'Кардамон · Сандал · Кедр',tone:'clay'},
 {brand:'Diptyque',name:'Philosykos',type:'unisex',price:15400,notes:'Инжир · Кокос · Древесина',tone:'green'},
 {brand:'Aesop',name:'Hwyl',type:'men',price:12600,notes:'Кипарис · Ладан · Ветивер',tone:'olive'},
 {brand:'Narciso Rodriguez',name:'For Her Musc Noir',type:'women',price:11200,notes:'Слива · Мускус · Замша',tone:'rose'},
 {brand:'Jo Malone',name:'Wood Sage & Sea Salt',type:'unisex',price:9800,notes:'Амброксан · Грейпфрут · Шалфей',tone:'blue'},
 {brand:'Kilian',name:'Angels’ Share',type:'unisex',price:33500,notes:'Коньяк · Корица · Бобы тонка',tone:'gold'}
];
let products=JSON.parse(localStorage.getItem('aura-products')||'null')||defaults,cart=[],filter='all',brandFilter='all';
const brands=['Afnan Perfumes','Aesop','Amouage','Byredo','Creed','Diptyque','Floraïku Paris','HFC Paris','Hormone Paris','Jo Malone','Kilian Paris','Lattafa Perfumes','Le Labo','Mancera Paris','Maison Crivelli Parfums','Maison Margiela','Memo Paris','Narciso Rodriguez','Parfums de Marly','Tom Ford','Xerjoff'];
const brandAliases={'Byredo':'BYREDO','Kilian Paris':'Kilian'};
const money=n=>n.toLocaleString('ru-RU')+' ₽'; const $=s=>document.querySelector(s);
function render(){let q=($('#search').value||'').toLowerCase(),selectedBrand=(brandAliases[brandFilter]||brandFilter).toLowerCase(),list=products.filter(p=>(filter==='all'||p.type===filter)&&(brandFilter==='all'||p.brand.toLowerCase()===selectedBrand)&&(`${p.brand} ${p.name} ${p.notes}`.toLowerCase().includes(q)));if($('#sort').value==='priceAsc')list.sort((a,b)=>a.price-b.price);if($('#sort').value==='priceDesc')list.sort((a,b)=>b.price-a.price);$('#resultCount').textContent=brandFilter==='all'?`${list.length} ароматов`:`${brandFilter} · ${list.length} ароматов`;
 $('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-art ${p.tone}"><span class="heart">♡</span><span class="mini-bottle">${p.brand[0]}</span><small>${p.type==='unisex'?'UNISEX':p.type==='women'?'POUR FEMME':'POUR HOMME'}</small></div><div class="product-info"><p>${p.brand}</p><h3>${p.name}</h3><small>${p.notes}</small><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-index="${products.indexOf(p)}">В корзину +</button></div></div></article>`).join(''):`<p class="empty">${brandFilter==='all'?'По вашему запросу ничего не найдено.':`У бренда ${brandFilter} пока нет товаров в нашей подборке.`}</p>`;document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.index]);renderCart();openDrawer()})}
function renderBrands(letter='all'){let list=letter==='all'?brands:brands.filter(b=>/^[0-9]/.test(b)?letter==='0-9':b[0].toUpperCase()===letter);$('#brandList').innerHTML=list.map(b=>`<button class="brand-item" data-brand-name="${b}">${b}<span>→</span></button>`).join('');document.querySelectorAll('.brand-item').forEach(b=>b.onclick=()=>{brandFilter=b.dataset.brandName;document.querySelectorAll('.brand-item').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#catalog').scrollIntoView({behavior:'smooth'});render()})}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItemsCount').textContent=cart.length?`(${cart.length})`:'';$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div class="cart-thumb ${p.tone}">${p.brand[0]}</div><div><b>${p.name}</b><small>${p.brand}</small></div><strong>${money(p.price)}</strong><button data-remove="${i}">×</button></div>`).join(''):'<p class="empty">Корзина пока пуста.<br>Добавьте аромат, который понравился.</p>';$('#cartTotal').textContent=money(cart.reduce((s,p)=>s+p.price,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}
function openDrawer(){$('#drawer').classList.add('open');$('#overlay').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});document.querySelectorAll('.brand-letter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.brand-letter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderBrands(b.dataset.brandLetter||'all')});$('#search').oninput=render;$('#sort').onchange=render;$('#openCart').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;$('#mobileMenu').onclick=()=>document.querySelector('.main-nav').classList.toggle('show');$('#checkout').onclick=()=>alert(cart.length?'Спасибо! Менеджер свяжется с вами для подтверждения заказа.':'Добавьте аромат в корзину.');$('#subscribe').onsubmit=e=>{e.preventDefault();alert('Спасибо! Вы подписаны на новости AURA.');e.target.reset()};renderBrands();render();renderCart();